version: '3.8'

networks:
  fluxo-net:
    driver: bridge

volumes:
  mysql_data:

services:
  mysql:
    container_name: container-bd
    image: vitorluzz/bd-fluxocerto
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: fluxoCerto
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - fluxo-net

  app:
    container_name: container-fluxocerto
    image: vitorluzz/fluxocerto
    restart: always
    ports:
      - "8080:8080"
    networks:
      - fluxo-net

  java:
    container_name: container-java
    image: openjdk:21-jdk
    tty: true
    networks:
      - fluxo-net